//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SqlResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SqlResources.SqlResources", typeof(SqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT C.CIFID,C.FullName,C.NRC,C.PhoneNo,A.AccountNo,AccountType,A.AccountStatus,A.Balance,A.AccountDescription
        ///FROM Customer_Table C INNER JOIN Account_Table A on C.CIFID=A.CustomerID WHERE C.IsActive=1 AND C.IsDeleted=0 AND AccountStatus=&apos;Active&apos;.
        /// </summary>
        public static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT C.CIFID FROM Customer_Table C INNER JOIN Account_Table A on C.CIFID=A.CustomerID
        ///WHERE C.IsActive=1 AND C.IsDeleted=0 AND AccountStatus=&apos;Active&apos; AND C.CIFID=@CIFID AND C.NRC=@NRC.
        /// </summary>
        public static string CheckAccount {
            get {
                return ResourceManager.GetString("CheckAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT C.CIFID,C.FullName FROM Customer_Table C INNER JOIN Account_Table A ON C.CIFID=A.CustomerID WHERE
        ///C.IsDeleted=0.
        /// </summary>
        public static string GetCustomerByAccountNo {
            get {
                return ResourceManager.GetString("GetCustomerByAccountNo", resourceCulture);
            }
        }
    }
}
